ICEWS14s:
  h_dim: 200
  num_hidden_layers: 2
  decoder: 'convtranse'
  encoder: 'uvrgcn'
  sequence: 'rnn'
  sequence_len: 3
  use_static: False
  weight: 0.5
  discount: 1
  angle: 10
  dropout: 0.2
  num_bases: 100
  num_basis: 100
  self_loop: True
  skip_connect: False
  input_dropout: 0.2
  hidden_dropout: 0.2
  feat_dropout: 0.2
  aggregation: 'none'
  entity_prediction: True
  relation_prediction: True
  opn: 'sub'
ICEWS18:
  h_dim: 200
  num_hidden_layers: 2
  decoder: 'convtranse'
  encoder: 'uvrgcn'
  sequence: 'rnn'
  sequence_len: 6
  use_static: False
  weight: 0.5
  discount: 1
  angle: 10
  dropout: 0.2
  num_bases: 100
  num_basis: 100
  self_loop: True
  skip_connect: False
  input_dropout: 0.2
  hidden_dropout: 0.2
  feat_dropout: 0.2
  aggregation: 'none'
  entity_prediction: True
  relation_prediction: True
  opn: 'sub'
ICEWS05-15:
  h_dim: 200
  num_hidden_layers: 2
  decoder: 'convtranse'
  encoder: 'uvrgcn'
  sequence: 'rnn'
  sequence_len: 5
  use_static: False
  weight: 0.5
  discount: 1
  angle: 10
  dropout: 0.2
  num_bases: 100
  num_basis: 100
  self_loop: True
  skip_connect: False
  input_dropout: 0.2
  hidden_dropout: 0.2
  feat_dropout: 0.2
  aggregation: 'none'
  entity_prediction: True
  relation_prediction: True
  opn: 'sub'
YAGO:
  h_dim: 200
  num_hidden_layers: 1
  decoder: 'convtranse'
  encoder: 'uvrgcn'
  sequence: 'regcn'
  sequence_len: 1
  use_static: False
  weight: 0.5
  discount: 1
  angle: 10
  dropout: 0.2
  num_bases: 100
  num_basis: 100
  self_loop: True
  skip_connect: False
  input_dropout: 0.2
  hidden_dropout: 0.2
  feat_dropout: 0.2
  aggregation: 'none'
  entity_prediction: True
  relation_prediction: True
  opn: 'sub'
WIKI:
  h_dim: 200
  num_hidden_layers: 2
  decoder: 'convtranse'
  encoder: 'uvrgcn'
  sequence: 'rnn'
  sequence_len: 2
  use_static: False
  weight: 0.5
  discount: 1
  angle: 10
  dropout: 0.2
  num_bases: 100
  num_basis: 100
  self_loop: True
  skip_connect: False
  input_dropout: 0.2
  hidden_dropout: 0.2
  feat_dropout: 0.2
  aggregation: 'none'
  entity_prediction: True
  relation_prediction: True
  opn: 'sub'
GDELT:
  h_dim: 200
  num_hidden_layers: 2
  decoder: 'convtranse'
  encoder: 'uvrgcn'
  sequence: 'rnn'
  sequence_len: 1
  use_static: False
  weight: 0.5
  discount: 1
  angle: 10
  dropout: 0.2
  num_bases: 100
  num_basis: 100
  self_loop: True
  skip_connect: False
  input_dropout: 0.2
  hidden_dropout: 0.2
  feat_dropout: 0.2
  aggregation: 'none'
  entity_prediction: True
  relation_prediction: True
  opn: 'sub'